# **1)Create a 1D NumPy array containing numbers from 1 to 10.**
**Question:**
**Use NumPy to create an array with numbers
from 1 to 10. Perform the following operations :**


**Find the sum of all elements.**


**Find the mean of the elements.**


**Find the standard deviation of the elements**

In [ ]:
import numpy as np

num = np.array([1,2,3,4,5,6,7,8,9,10])

print(num)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
print(np.sum(num))

55


In [ ]:
print(np.mean(num))

5.5


In [ ]:
import numpy as np

num = np.array([1,2,3,4,5,6,7,8,9,10])

std_deviation = np.std(num)

sum_std_deviation = std_deviation + std_deviation

print("Standard deviation:", std_deviation)
print("")
print("Sum of the standard deviation with itself:", sum_std_deviation)

Standard deviation: 2.8722813232690143

Sum of the standard deviation with itself: 5.744562646538029


# **2)Indexing in 1D arrays.**
**Question:**
**Given the array arr = np.array([10, 20, 30, 40, 50, 60]), perform the
following operations:**


**Extract the second and fourth elements.**

**Extract all elements from the third element onwards.**

**Reverse the array using slicing.**

In [9]:
import numpy as np
arr = np.array([10,20,30,40,50,60])
print(arr)

print(arr[1],arr[3])

[10 20 30 40 50 60]
20 40


In [10]:
print(arr[3:])

[40 50 60]


In [16]:
print(arr[::-1])

[60 50 40 30 20 10]


# **3)Reshape a 1D array into a 2D array.**
**Question:**

**Create a 1D array with 12 elements, ranging from 1 to 12.
Reshape it into a 3x4 array.**

In [21]:
import numpy as np

one = np.arange(1,13)

print(one)


[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [23]:
x = one.reshape(3,4)
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


# **4)Element-wise operations.**
**Question:**

**Given two arrays A = np.array([1, 2, 3]) and B = np.array([4, 5, 6]), perform
the following operations:**

**Add the two arrays.**

**Subtract the second array from the first.**

**Multiply the two arrays element-wise.**

**Divide the first array by the second**

In [24]:
import numpy as np

A = np.array([1,2,3])

B = np.array([4,5,6])

print(A)

print('-' *30)

print(B)

print('-' *30)

[1 2 3]
------------------------------
[4 5 6]
------------------------------


In [25]:
#Add

print(np.add(A,B))

[5 7 9]


In [27]:
#Subtract

print(np.subtract(A,B))

[-3 -3 -3]


In [28]:
#Multiply

print(np.multiply(A,B))

[ 4 10 18]


In [29]:
#Division

print(np.divide(A,B))

[0.25 0.4  0.5 ]
